### ISSUE TITLE
"After scenario" hook is executed before test case from scenario outline is finished

### ISSUE THREAD

**Issue by alexiel15** [allure-framework/allure-cucumber#15]
Hi again! :)

I've encountered some problems with scenario outlines!

I want to get the time of test-case stop from the "After scenario" hook.
I found out that I'm not able to do that in scenario outlines because the steps stop only after the hook is executed!
For example, I have:

```cucumber
Scenario outline: Test
Given I'm on main page
I should see "<text>"
Examples:
|text1|
|text2|
```

Then, in my After scenario hook I print something. And when I run the tests, this is what I see:
```
Starting step FEATURE Example: | text1 |.I'm on main page
Starting step FEATURE Example: | text1 |.I should see "<text1>"
...here I see what I printed in After...
Stopping step FEATURE Example: | text1 |.I'm on main page
Stopping step FEATURE Example: | text1 |.I should see "<text1>"
```
I think it would be more correct to execute After scenario hook after each example from scenario outline is stopped.

And also, it seems that the time in scenario outline test-cases is counted incorrectly, because the latest step is always much longer than the others

**Comment by 9ikhan** [comment]
@alexiel15 - Can you try the `0.5.0` version.
