### ISSUE TITLE
Support for issue attachments 

### ISSUE THREAD

**Issue by vase4kin** [allure-framework/allure-cucumber#20]
Hello guys, would you kindly help me is there any work to provide support for attaching [issues](https://github.com/allure-framework/allure-core/wiki/Issues)?
Thanks!

**Comment by 9ikhan** [comment]
I'll explore this and keep you posted.

**Comment by izhilenkov** [comment]
any news? can you tell when you'll fix it? i need to attach screenshots so much :(

**Comment by 9ikhan** [comment]
@izhilenkov - even now you can attach screenshots. It's just that integration with issue-tracker is missing.

I'm currently working on `allure-cucumber` for `cucumber 2.0.0` which requires lot of refactoring. I'll plan to finish this refactoring this weekend and then I'll work on this issue.

**Comment by izhilenkov** [comment]
Oh, I'm so sorry for that.
But... Can you explain me what I do wrong? 
I use: 
ruby 1.9.3
cucumber 1.3.18
allure-cucumber 0.4.4 
```ruby
# file: features/support/env.rb
require 'cucumber'
require 'allure-cucumber'
require 'allure-cucumber/dsl'

include AllureCucumber::DSL
After do
  attach_file("file_title", "C:/screens/screenshot.png")
end
```
And while tests running, after each test I can see in log
``` 
Adding attachment file_title to Authorize as user.Not authorize.I see fail
```
But when I open result xml, I can't find any attachments :(
```xml
   <steps>
        <step start="1427874028453" stop="1427874035435" status="passed">
          <name>I open "landing page"</name>
          <title>I open "landing page"</title>
          <attachments/>
        </step>
        <step start="1427874035435" stop="1427874036194" status="passed">
          <name>I click on login button</name>
          <title>I click on login button</title>
          <attachments/>
        </step>
        <step start="1427874036194" stop="1427874036549" status="passed">
          <name>I see a login container</name>
          <title>I see a login container</title>
          <attachments/>
        </step>
        <step start="1427874036549" stop="1427874038692" status="passed">
          <name>I type "blablabla@mail.ru" as login and "fail_pass" as password</name>
          <title>I type "blablabla@mail.ru" as login and "fail_pass" as password</title>
          <attachments/>
        </step>
        <step start="1427874038692" stop="1427874039012" status="passed">
          <name>I click login</name>
          <title>I click login</title>
          <attachments/>
        </step>
        <step start="1427874039012" stop="1427874039013" status="pending">
          <name>I see fail</name>
          <title>I see fail</title>
          <attachments/>
        </step>
      </steps>
      <attachments/>
```

**Comment by 9ikhan** [comment]
Second argument to `attach_file` must be a file, not filepath.

Can you try this?
 
```ruby
include AllureCucumber::DSL
After do
  attach_file("file_title", File.open("filepath_as_string"))
end
```

**Comment by izhilenkov** [comment]
@9ikhan oh, God... That is my bad... Thank a lot for so fast answer. My problem is solved. Of course a "file" as a file, not filepath...

**Comment by farooqyousuf** [comment]
Thanks so much for this question and answer, I've been looking the whole day for this!!!

**Comment by 9ikhan** [comment]
>Hello guys, would you kindly help me is there any work to provide support for attaching issues?
Thanks!

@smecsia Will it be ok if we do this via a cucumber tag like `@issue-1` where `issue` is a pre-defined keyword and `1` is the issue number ? or is there a better way to handle this ?

**Comment by smecsia** [comment]
@9ikhan I believe this would be OK. At least I don't know a better way to do it.

**Comment by tk8817** [comment]
@9ikhan & @smecsia , I have a solution for this in which the user would use the configure block to set their prefix that would indicate a tag is to be seen as an issue. 

```ruby
AllureCucumber.configure do  |c| 
  c.output_dir = 'allure-results/' 
  c.issue_preifix = 'JIRA-'
end
```

```ruby 
  @start_video @JIRA-CC-1088
  Scenario: Example Tests
    Given I am a new visitor
    When I go to the home-page
    Then  I should be on the home-page
```

In this case, the Allure Cucumber formatter will see the tag @JIRA-CC-1088, parse out the prefix - and attach an issue link of 'CC-1088'

**Comment by smecsia** [comment]
@tk8817 Feel free to create a PR.

**Comment by tk8817** [comment]
@smecsia the PR is up, along with a few others.

**Comment by Fulcrum81** [comment]
Hi all,

I'm facing the following issue:
I need to attach a screenshot of each step regardless if it's successful or not. to the report (yeah, yeah, I know it sounds weird but that's the way it is).
I'm using the AfterStep method and the problem is that the FeatureTracker interprets it as a separate step with the name "AfterStep hook" so instead of attaching the file to the current step the extra step with the name "AfterStep hook" is added to the report right after the first step.
Moreover on further calls of AfterStep hook instead of adding the new "AfterStep hook" after the next step it overwrites the previous one.
So I end up with the report that has the first step, then the "AfterStep hook" step with the last screenshot attached and then all the remaining steps in their usual order.

Question: can I somehow pass the actual step name to the FeatureTracker from AfterStep instead of the "AfterStep hook"?

**Comment by tk8817** [comment]
This issue can now be closed.

**Comment by 9ikhan** [comment]
@Fulcrum81 - Please open a new issue. I'll look into it. What your are facing is unrelated to this topic.

**Comment by LukaBrazi** [comment]
Hi to all i have same problem
 I using this construction

After do |scenario|
  @browser.save_screenshot if scenario.failed?
  include AllureCucumber::DSL
  attach_file("07Apr2017114056.png",File.open("../../src/screen/07Apr2017114056.png"))
  @browser.quit
end
but it dont work and give me erorr msg:
 Errno::ENOENT: No such file or directory @ rb_sysopen - ../../src/screen/07Apr2017114056.png What i do wrong?
