### ISSUE TITLE
Report version 1.4.0 support

### ISSUE THREAD

**Issue by vase4kin** [allure-framework/allure-cucumber#21]
Hello, guys!
Does cucumber adapter support report version 1.4.0?
I faced the problem with skipped tests. They don't appear in report on this version.
 
On the overview screen there is some white space instead of skipped tests results.
![image](https://cloud.githubusercontent.com/assets/4580186/6850763/a3236f48-d40d-11e4-8ff8-c97b0080d46c.png)

Thanks for help!

**Comment by vania-pooh** [comment]
@vase4kin I would say this adapter was implemented uniquely for 1.4.x series. But let's wait for @9ikhan to give some comments.

**Comment by 9ikhan** [comment]
Sorry guys, I have been very busy recently and have not been able to look into the issues. Give me some time to replicate the issue then I'll get back on this.

**Comment by vase4kin** [comment]
Closed. Not reproduced on latest version.
