### ISSUE TITLE
Changes in cucumber api cause exception when executing tests with formatter

### ISSUE THREAD

**Issue by vase4kin** [allure-framework/allure-cucumber#22]
Hello guys!
Just update dependencies to latest version and you will get the exception:
````
Cucumber::Ast` no longer exists. These classes have moved into the `Cucumber::Core::Ast` namespace, but may not have the same API. (RuntimeError)
/Users/vase4kin/.rvm/gems/ruby-2.1.5/gems/cucumber-2.0.0/lib/cucumber/ast.rb:10:in `const_missing'
/Users/vase4kin/.rvm/gems/ruby-2.1.5/gems/allure-cucumber-0.4.4/lib/allure-cucumber/formatter.rb:35:in `before_feature_element'
...
```
Btw, i tried to make a fix by myself, but i noticed that you don't have any tests in your project. It will be more helpful for contributing if you add some.
Thanks!

**Comment by 9ikhan** [comment]
Thanks @vase4kin  I see the problem. I'll work also on the tests.

@smecsia @vania-pooh - Need your suggestion. Should we just support cucumber 2.0.0 onwards (There are lot of API changes) or should the adapter be backward compatible?

**Comment by vania-pooh** [comment]
@9ikhan I would opt for releasing a new major version when Cucumber version gets increased.

**Comment by smecsia** [comment]
I agree with Ivan. May be it is worth to create the new branch for the newer version of Cucumber.

**Comment by atykhonov** [comment]
Hi,

is there any chance to have a fix for cucumber 2.0.0?

**Comment by 9ikhan** [comment]
Sorry for the delay. I have been with very busy with work lately. I will push the changes in a separate branch for `normal scenarios` and keep working on `scenario outlines`(as major refactoring is required for this).

**Comment by atykhonov** [comment]
@9ikhan thank you!

**Comment by 9ikhan** [comment]
@vase4kin @atykhonov - Released a new version `0.5.0` which fixes this issue. Please check it and let me know if it works for you.

**Comment by ajit-jadhav** [comment]
@9ikhan No, it is still showing same error message. like `Cucumber::Ast` no longer exists. These classes have moved into the `Cucumber::Core::Ast` namespace,`

**Comment by 9ikhan** [comment]
Which version of `allure-cucumber` and `cucumber` are you using? This gem has dependency >= `cucumber 2.0.0` and `Cucumber::Ast` is no longer [used](https://github.com/allure-framework/allure-cucumber/blob/master/lib/allure-cucumber/formatter.rb#L32)
