### ISSUE TITLE
Add Specs 

### ISSUE THREAD

**Issue by 9ikhan** [allure-framework/allure-cucumber#23]
I have been thinking about adding specs or taking a TDD approach for the refactoring. But this adaptor is more of a middleware which gets hooks from cucumber processes them and sends requests to `ruby-adaptor-api`. The processing is minimal. What could be the best strategy to write unit tests or specs here? Any examples or links would be much appreciated.

**Comment by tk8817** [comment]
we can use RSpec + doubles to mock the objects which allure-cucumber expects. A good place to look for inspiration would be other cucumber formatters.

**Comment by andrcuns** [comment]
Implemented in https://github.com/allure-framework/allure-ruby/tree/master/allure-cucumber
