### ISSUE TITLE
Option to disable output into $stdout in AllureRubyAdaptor::Builder

### ISSUE THREAD

**Issue by vgrigoruk** [allure-framework/allure-cucumber#25]
Need a way to make output less verbose when using AllureCucumber::Formatter.

E.g. this puts statement could check a config option as a condition to be executed:
```
          puts "Starting case_or_suite #{suite} with labels #{labels}"
```

**Comment by smecsia** [comment]
@vgrigoruk thanks. This is duplicate of https://github.com/allure-framework/allure-ruby-adaptor-api/issues/6
