### ISSUE TITLE
Any current way or future plans to support running Cukes with the parallel_tests gem?

### ISSUE THREAD

**Issue by farooqyousuf** [allure-framework/allure-cucumber#26]

**Comment by smecsia** [comment]
@farooqyousuf Have you tried just to run your features like so?
```bash
parallel_cucumber features/ -o "--format AllureCucumber::Formatter"
```

**Comment by farooqyousuf** [comment]
@smecsia Thanks, that worked. I wasn't sure how Allure would generate reports with parallel_gems since parallel_gems executes different instances, but for each instance it's just giving a separate xml file it seems. Thanks again, really appreciate your help!
