### ISSUE TITLE
Showing the scenario tags in Allure cucumber report

### ISSUE THREAD

**Issue by ducthanh** [allure-framework/allure-cucumber#32]
Hello,
I am using cucumber for doing my company user acceptance test, we use Allure Reporter and it's really a great reporter. Actually we use the cucumber tags to manage our test suite and we want to show the tags that the single scenario is belong to. I've tried to find the solution for it but there was no clues for that. It looked like Allure report didn't support to get the tags from an executing scenario. 

Could anyone please suggest me some ideal for it?

Thank you

**Comment by tk8817** [comment]
++ on this issue, any advice devs? Is this something that could be supported by Allure? If so, I would be happy to investigate and cook up a PR.

**Comment by smecsia** [comment]
Summoning @baev

**Comment by tk8817** [comment]
@baev I saw your response on a similar issue in Allure Core 
https://github.com/allure-framework/allure-core/issues/764

I will work on adding this into allure-cucumber, fingers crossed the saw functions are exposed in the ruby API bindings

**Comment by tk8817** [comment]
We need functionality in allure-core to make this happen. Specfically, we need an unique indexed tag type which can take any string as input.

**Comment by webmagit** [comment]
@baev @smecsia does this mean annotations in a feature file cannot be used to show up as "Stories" and "Features" on the Allure report?

**Comment by baev** [comment]
@tk8817 you can create label (name: tag, value: some-value) and it will be shown in the report like this:
![screen shot 2017-10-10 at 14 25 36](https://user-images.githubusercontent.com/2149631/31384280-f2eac676-adc6-11e7-86bc-339bf202c60e.png)

**Comment by andrcuns** [comment]
This is implemented in new adaptor implementation v2.13.0
