### ISSUE TITLE
Incorrect Output for Scenarios Failing in Before Step

### ISSUE THREAD

**Issue by tk8817** [allure-framework/allure-cucumber#33]
Hi folks. For scenarios which fail in the Before hook, example: 

``` ruby 
Before do |scenario|
  raise 'Test Failed On Purpose' 
end
```

I noted the following.

1) Allure marks the scenario as pending 
2) No exception/stacktrace is attached to the scenario in Allure 

I believe if an exception is raised in a Before step, then the scenario should be marked as Failed, moreover the raised error should be shown correctly in the report. 

Best,
Justin

**Comment by 9ikhan** [comment]
Yeah. Just saw that we don't override `before_scenario` and `after_sceanrio` hooks. Can you fix it and send a PR?

**Comment by tk8817** [comment]
@9ikhan , working on one :)

**Comment by tk8817** [comment]
@9ikhan I am hesitant to continue as my design is starting to require a drastic change to when/how the stop_test is called. Would prefer your input before continuing.

As it stands ```after_steps``` is handling ```stop_test``` & ```test_result``` calls. Unfortunately, ```after_steps``` is called BEFORE ```after_scenario``` -- which means I cannot extract ```scenario.status``` from  ```after_scenario``` in time for the test teardown.

To resolve this I looked into moving the ```stop_test``` & ```test_result``` calls to ```after_scenario``` but  ```after_steps``` takes ```steps``` as input, while ```after_scenario``` takes ```scenario```. As such, the teardown fails due to not having the correct info (missing exception & step data). 

To come to a full solution I foresee needing to split the collection of data between ```after_steps``` and ```after_scenario``` which would mean a modest rewrite of stop_test to handle getting data at 2 different stages.

**Comment by tk8817** [comment]
Found the details I need to get the exception captured, will have the PR updates on Monday. 

https://github.com/cucumber/cucumber-ruby/blob/master/features/docs/exception_in_before_hook.feature

**Comment by tk8817** [comment]
This is fixed now.
