### ISSUE TITLE
AllureCucumber::DSL.attach_file failing with "Closed Stream" error

### ISSUE THREAD

**Issue by rahulvig** [allure-framework/allure-cucumber#36]
Hi,

I am seeing this issue for the past 2 weeks where the attach_file in my After hooks is failing with "Closed Stream" error.

**Comment by 9ikhan** [comment]
Can you also specify the allure-cucumber version, ruby version and console output? It will help us debug faster.

**Comment by rahulvig** [comment]
Hi Imran,
The versions are as follows-
cucumber 2.1.0
allure-cucumber 0.5.0
ruby 2.2.0

The console output is showing-

> 
>    scenario name is Requestor should be able to add a new Briefing
>       The file is: #<File:0x00000007b64fc0>
>       The file patch is artifacts/screenshots/Requestor should be able to add a new Briefing.png
>       Does the file exist true
>       Is the file readable true
>       closed stream (IOError)
>       ./features/support/hooks.rb:88:in `After'

here is how my hooks.rb looks like-

```
def take_screenshot(scenario_name)
    screenshots_path= 'artifacts/screenshots/'
    unless File.directory?(screenshots_path)
        FileUtils.mkdir_p(screenshots_path)
    end
    puts "scenario name is  #{scenario_name}"
    page.driver.browser.save_screenshot "#{screenshots_path}/#{scenario_name}.png"
end
*******
    if scenario.failed?
        path = take_screenshot(scenario.name)
        puts "path to attach #{path}"
        AllureCucumber::DSL.attach_file("#{scenario.name}.png -FAILURE Screenshot", path) if ENV['ALLURE']=='true'
    end
```

**Comment by rahulvig** [comment]
Hi,

I did more investigation and found out that the line-
`AllureCucumber::DSL.attach_file("#{scenario.name}.png -FAILURE Screenshot", path) if ENV['ALLURE']=='true'`

is actually referring to the attach_file method in capybara gem - 
[https://github.com/jnicklas/capybara/blob/master/lib/capybara/node/actions.rb](url)

and failing. I am not sure why this is happening.

**Comment by rahulvig** [comment]
Not an issue. The Capybara base methods were getting initialised from inside a step. Thanks!
