### ISSUE TITLE
[Feature Request] Add possibility to set several "issue" tags

### ISSUE THREAD

**Issue by CoHuK** [allure-framework/allure-cucumber#44]
Currently, if you setting 2 tags for an issue, allure generates report only with last one.
It will be great to have the possibility to set several issues for one test.

@tk8817 Maybe you can help?

**Comment by tk8817** [comment]
@CoHuK I think this is a design in the core allure framework to only accept one entry per tag, my PR will iterate over every tag and indeed it will submit all of them to the allure API adapter. 

@9ikhan can you confirm?

**Comment by CoHuK** [comment]
@tk8817 https://github.com/allure-framework/allure-core/wiki/Issues It works with multiple issues.

**Comment by CoHuK** [comment]
No news? :(

**Comment by 9ikhan** [comment]
I haven't got chance to work on the project in last few months. I can review and merge if you can send a PR.

**Comment by andrcuns** [comment]
This is implemented in new adaptor implementation v2.13.0
