### ISSUE TITLE
get an error when using allure-cucumber.

### ISSUE THREAD

**Issue by imzzy** [allure-framework/allure-cucumber#45]
hi, i am using allure to my cucumber-ruby feature, here is my env:
i am using the feature file: https://github.com/cucumber/cucumber-ruby/tree/master/examples/i18n/en
when not use allure. just run command 'cucumber',  it worked,

however, when i use allure and add "require 'allure-cucumber'" to env.rb file. run command 'cucumber  --format AllureCucumber::Formatter' . i got an error:

`DEPRECATION: Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from /Users/zack-zhao/Desktop/cucumber-ruby-master/examples/i18n/en/features/step_definitions/calculator_steps.rb:23:in `block in <top (required)>'.
undefined method `[]=' for nil:NilClass (NoMethodError)
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/allure-cucumber-0.5.6/lib/allure-cucumber/formatter.rb:82:in `after_scenario'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/allure-cucumber-0.5.6/lib/allure-cucumber/formatter.rb:87:in `after_feature_element'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/ignore_missing_messages.rb:10:in `method_missing'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:622:in `after'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:309:in `after'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:104:in `feature'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/ast/describes_itself.rb:6:in `describe_to'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:35:in `block in describe_source_to'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:34:in `each'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:34:in `describe_source_to'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:86:in `before_test_case'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:28:in `before_test_case'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:16:in `block in method_missing'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:15:in `each'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:15:in `method_missing'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:17:in `test_case'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/apply_around_hooks.rb:8:in `test_case'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/apply_after_hooks.rb:5:in `test_case'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/apply_before_hooks.rb:5:in `test_case'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/apply_after_step_hooks.rb:8:in `test_case'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/activate_steps.rb:11:in `test_case'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/quit.rb:11:in `test_case'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `block in done'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `each'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `done'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/filter.rb:61:in `done'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/compiler.rb:23:in `done'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/gherkin/parser.rb:35:in `done'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core.rb:29:in `parse'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core.rb:18:in `compile'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:67:in `run!'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
/Users/zack-zhao/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
/Users/zack-zhao/.rbenv/versions/2.3.1/bin/cucumber:23:in `load'
/Users/zack-zhao/.rbenv/versions/2.3.1/bin/cucumber:23:in `<main>'`

please help me. thank you. :)

**Comment by imzzy** [comment]
however, when i eidt the addition.feature file: delete the examples and change  Scenario Outline to  Scenario then run command 'cucumber  --format AllureCucumber::Formatter', it working.

Does it have some bugs with Scenario Outline and examples in the feature?

**Comment by 9ikhan** [comment]
@imzzy  - Thanks for pointing out the issue. I have not been able to run these features locally as `Nokogiri`is not getting installed. I'm working on it.

**Comment by imzzy** [comment]
thank you.

**Comment by 9ikhan** [comment]
Can you check if this is still an issue with `0.5.7` version.

**Comment by tk8817** [comment]
This should be fixed in the latest release @imzzy

**Comment by imzzy** [comment]
@9ikhan @tk8817  yes. it has been fixed in the 0.5.7 version .thanks :)
