### ISSUE TITLE
Add automated tests to check 'attach file' functionality

### ISSUE THREAD

**Issue by elzenar** [allure-framework/allure-cucumber#50]
Hello.

I am using allure-cucumber. And I think I have found several issues in 'attach file' functionality.
I have created some automated tests to indicate found issues.
I would like to add these tests into main repository.
May I do it ? Do you need such contribution ?

**Comment by tk8817** [comment]
@elzenar tests are 100% welcome, we need them! Thank you very much!

**Comment by elzenar** [comment]
@tk8817 
Hello, Justin.
Please review the tests and give me a feedback.

Also I already have a vision how to fix AllureCucumber for failed scenarios. So I can share it too.

**Comment by elzenar** [comment]
Hello @tk8817 
Thank you for your activity to merge the tests.
As for me this issue can be closed.
If you have no objection, I will close it. 
(And I will open a new issue about attaching :) )

**Comment by tk8817** [comment]
Cheers!
