### ISSUE TITLE
Release new gem version

### ISSUE THREAD

**Issue by tk8817** [allure-framework/allure-cucumber#52]
summon @baev and @9ikhan - I do not have permissions to push to rubygems, but we have some great updates in master that need to be released.

**Comment by smecsia** [comment]
@tk8817 if you tell me your email, I'll add you to the owners of `allure-ruby-adaptor-api` and `allure-rspec` gems.
BTW @9ikhan let's add all main allure devs (including @tk8817) to the gem owners.

**Comment by tk8817** [comment]
@smecsia jcommu@gmail.com

**Comment by smecsia** [comment]
@tk8817 done.

**Comment by smecsia** [comment]
@tk8817 yo've closed it too early. We should still wait until @9ikhan add us as owners to allure-cucumber (I'm not the owner of it)...

**Comment by 9ikhan** [comment]
I'll do it.

**Comment by 9ikhan** [comment]
@tk8817 @smecsia - Give me your email id used for rubygems.org account.

**Comment by smecsia** [comment]
@9ikhan `smecsia@list.ru` is mine. And if you make me the owner, I'll add @tk8817 as an owner, since I have his email now.

**Comment by 9ikhan** [comment]
Done.
