### ISSUE TITLE
Add 'embed' method to add attachments in a common way in Cucumber

### ISSUE THREAD

**Issue by elzenar** [allure-framework/allure-cucumber#53]
In order to save the time for creating a working infrastructure for automated tests
As a QA engineer 
I want to use the same API for attaching images into different reports (including Allure report).

Cucumber's formatters have 'embed' method for adding attachments. 
```
# This is a code of 'embed' from Cucumber::Formatter::Html class

      def embed(src, mime_type, label)
        case(mime_type)
        when /^image\/(png|gif|jpg|jpeg)/
          unless File.file?(src) or src =~ /^data:image\/(png|gif|jpg|jpeg);base64,/
            type = mime_type =~ /;base[0-9]+$/ ? mime_type : mime_type + ";base64"
            src = "data:" + type + "," + src
          end
          embed_image(src, label)
        when /^text\/plain/
          embed_text(src, label)
        end
      end
```

I propose to add similar method to 'allure-cucumber'.

Just for information: I already have a working code for this issue so I can make a merge request for that functionality.

**Comment by elzenar** [comment]
@tk8817 
Hello, Justin!
Could you review this issue ?

**Comment by 9ikhan** [comment]
I would not like to remove `attach_file` method for compatibility reasons. We can provide support for both - `embed` and `attach_file` method. Can you send a PR?

**Comment by 9ikhan** [comment]
I believe, this method is specific to HTML formatter.  Still, can you send a PR with support for both `embed` and `attach_file` methods?

**Comment by elzenar** [comment]
@9ikhan 
Yes, I can. I will do it. :)
