### ISSUE TITLE
Continue to update?

### ISSUE THREAD

**Issue by Richard-Cao** [allure-framework/allure-cucumber#59]
I see very few updates recently.

**Comment by baev** [comment]
@Richard-Cao hi! Allure Cucumber was created by our community and the core team has no Ruby devs. So it would be nice if you help us to update it. At least point to high priority issues that should be fixed ASAP

**Comment by mikesalvia** [comment]
@baev I am a Ruby developer and actively using Allure Cucumber. I will see if I can contribute!

**Comment by baev** [comment]
@mikesalvia 👍

**Comment by mikesalvia** [comment]
@baev I actually started work today on something that has been plaguing our team! When having duplicate steps in a scenario, the steps are keyed by "step_name" which caused them to not be ordered correctly. I will add you to my PR as a reviewer... There is only in `allure-cucumber` and one in `allure-ruby-commons`.

**Comment by baev** [comment]
@mikesalvia thanks for all the work, I wish you will continue to update the project. 

IMHO the first priority is to update to new formatter API https://github.com/allure-framework/allure-cucumber/issues/63 and adding specs for it.

**Comment by baev** [comment]
@mikesalvia BTW you can [DM me in gitter](https://gitter.im/baev) to ask any related questions
