### ISSUE TITLE
Failed screenshots are not attached to the generated HTML report

### ISSUE THREAD

**Issue by prashanth-sams** [allure-framework/allure-cucumber#67]
The **.json** file under `allure-report > data > test-cases` is not updating the failure screenshot attachments that was actually populated during tests.

run the below cmd to obtain data as in the below screenshot:
```
cucumber features/scenarios/*/*.feature --format AllureCucumber::Formatter
allure serve gen/allure-results/
```

![Result](https://i.imgur.com/93t7g8V.png)

![Result](https://i.imgur.com/nXzu2oQ.png)

**Version used:**
selenium webdriver: 3.13.0
cucumber: 3.1.0
allure-cucumber: 0.6.1

**Comment by andrejska** [comment]
looks very similar to https://github.com/allure-framework/allure-cucumber/issues/68
@prashanth-sams please try my fix:
```
  gem 'allure-cucumber', branch: 'master', git: 'https://github.com/andrejska/allure-cucumber'
  gem 'allure-ruby-adaptor-api', branch: 'master', git: 'https://github.com/andrejska/allure-ruby-commons'
```

**Comment by prashanth-sams** [comment]
hey @andrejska, so, the fix is merged from your fork to https://github.com/allure-framework/allure-cucumber ?

**Comment by andrejska** [comment]
@prashanth-sams not yet, but if you want you can try my fix in your project by using provided snippet in your gemfile

**Comment by prashanth-sams** [comment]
@andrejska ah okay; thanks 💯

**Comment by prashanth-sams** [comment]
@baev can you please merge https://github.com/allure-framework/allure-cucumber/pull/70 in master; it would be helpful for most of the allure users
