### ISSUE TITLE
Not Attachs screenshots in reports

### ISSUE THREAD

**Issue by jeancrb19** [allure-framework/allure-cucumber#69]
Hi i have this error 
`undefined method `step_name' for nil:NilClass (NoMethodError)
/home/mtzcpd1222/.rvm/gems/ruby-2.4.4/gems/allure-cucumber-0.6.1/lib/allure-cucumber/dsl.rb:7:in `attach_file'
/home/mtzcpd1222/Workspace/Fleury/features/support/env.rb:18:in `block in <top (required)>'
/home/mtzcpd1222/.rvm/gems/ruby-2.4.4/gems/allure-cucumber-0.6.1/lib/allure-cucumber.rb:45:in `configure'
/home/mtzcpd1222/Workspace/Fleury/features/support/env.rb:11:in `<top (required)>'
/home/mtzcpd1222/.rvm/gems/ruby-2.4.4/gems/cucumber-3.1.0/lib/cucumber/glue/registry_and_more.rb:106:in `load'
/home/mtzcpd1222/.rvm/gems/ruby-2.4.4/gems/cucumber-3.1.0/lib/cucumber/glue/registry_and_more.rb:106:in `load_code_file'
/home/mtzcpd1222/.rvm/gems/ruby-2.4.4/gems/cucumber-3.1.0/lib/cucumber/runtime/support_code.rb:147:in `load_file'
/home/mtzcpd1222/.rvm/gems/ruby-2.4.4/gems/cucumber-3.1.0/lib/cucumber/runtime/support_code.rb:88:in `block in load_files!'
/home/mtzcpd1222/.rvm/gems/ruby-2.4.4/gems/cucumber-3.1.0/lib/cucumber/runtime/support_code.rb:87:in `each'
/home/mtzcpd1222/.rvm/gems/ruby-2.4.4/gems/cucumber-3.1.0/lib/cucumber/runtime/support_code.rb:87:in `load_files!'
/home/mtzcpd1222/.rvm/gems/ruby-2.4.4/gems/cucumber-3.1.0/lib/cucumber/runtime.rb:270:in `load_step_definitions'
/home/mtzcpd1222/.rvm/gems/ruby-2.4.4/gems/cucumber-3.1.0/lib/cucumber/runtime.rb:67:in `run!'
/home/mtzcpd1222/.rvm/gems/ruby-2.4.4/gems/cucumber-3.1.0/lib/cucumber/cli/main.rb:33:in `execute!'
/home/mtzcpd1222/.rvm/gems/ruby-2.4.4/gems/cucumber-3.1.0/bin/cucumber:9:in `<top (required)>'
/home/mtzcpd1222/.rvm/gems/ruby-2.4.4/bin/cucumber:23:in `load'
/home/mtzcpd1222/.rvm/gems/ruby-2.4.4/bin/cucumber:23:in `<main>'
/home/mtzcpd1222/.rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:15:in `eval'
/home/mtzcpd1222/.rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:15:in `<main>'`

**env.rb**

`require 'selenium-webdriver'
require 'allure-cucumber'

include AllureCucumber::DSL

screenshot = '/data/allure-reports/batata.png'
AllureCucumber.configure do |c|
    c.clean_dir = false
    c.severity_prefix = '@URGENCY:'
    c.output_dir = '/data/allure-reports/'
    c.attach_file('screenshot', screenshot)
end`

**Environment:**
Ruby 2.4.4
   Cucumber 3.1
   allure-cucumber (0.6.1)
Allure 2.5.0

**Comment by andrejska** [comment]
looks very similar to #68
@jeancrb19 please try my fix:
```
  gem 'allure-cucumber', branch: 'master', git: 'https://github.com/andrejska/allure-cucumber'
  gem 'allure-ruby-adaptor-api', branch: 'master', git: 'https://github.com/andrejska/allure-ruby-commons'
```
