### ISSUE TITLE
Suport for attachments

### ISSUE THREAD

**Issue by maysamms** [allure-framework/allure-cucumber#71]
Hi guys. I need a support for attach_file ... If anyone can help me, please

I'm using:
cucumber 3.1.2
capybara 3.2.1
rspec 3.7
allure-cucumber 0.6.1

I've tried using attach_file in several ways, but it does not attach the .png image attachment to the report

Can someone show me an example of how to use it so I can see if I'm using it correctly, please?

**Comment by Leandro-b-03** [comment]
Hey, @maysamms, try to use `embed` instead

```ruby
    embed(File.open(file_path), 'image/png', file_name)
```

**Comment by maysamms** [comment]
> 
> 
> Hey, @maysamms, try to use `embed` instead
> 
> ```ruby
>     embed(File.open(file_path), 'image/png', file_name)
> ```

It worked!
Thank you :)
