### ISSUE TITLE
No report generated for retries after parallel test run

### ISSUE THREAD

**Issue by violettka** [allure-framework/allure-cucumber#80]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Some of the rerun tests aren't included into the report. Report shows up the first run results, though the console logs shows successful rerun. Doesn't happen for all scenarios. May be related to parallel run.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Pre-conditions:
1. Rerun implemented for failing tests
2. Do not clean report folder after the first run

Steps
1. Fail the test during the first run
2. Ensure the test passed after rerun
3. Generate a report

#### What is the expected behavior?
Report contains passed test. 

#### Please tell us about your environment:

| Allure version | 2.6.0 |
| Test framework | cucumber@3.1.1 |
| Allure adaptor | allure-cucumber@0.6.1 |
| Generate report using | allure2 |
| Parallel_tests gem| parallel_tests(2.21.3) |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by andrcuns** [comment]
Should be solved in new adaptor implementation v2.13.0
