### ISSUE TITLE
Reports are not getting created when running the tests with cucumber - capybara - selenium

### ISSUE THREAD

**Issue by nareshnavinash** [allure-framework/allure-cucumber#82]
I am trying to run the cucumber test cases along with capybara and selenium webdriver. while running i am getting the following error even if all the test cases are passed, as a result,
# cucumber jenkins job is getting failed.
# when i try to open the allure report, allure report is blank.

Can any one help me out from this.

log trace :

3 scenarios (0 failed, 3 passed)
12 steps (0 failed, 12 passed)
1m8.278s

wrong number of arguments (given 1, expected 0) (ArgumentError)
/Users/user/.rvm/gems/ruby-2.6.0/gems/capybara-3.12.0/lib/capybara/node/document.rb:31:in `title'
/Users/user/.rvm/gems/ruby-2.6.0/gems/capybara-3.12.0/lib/capybara/session.rb:738:in `block (2 levels) in <class:Session>'
/Users/user/.rvm/gems/ruby-2.6.0/gems/capybara-3.12.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
/Users/user/.rvm/gems/ruby-2.6.0/gems/allure-ruby-adaptor-api-0.7.2/lib/allure-ruby-adaptor-api/builder.rb:128:in `block (3 levels) in build!'
/Users/user/.rvm/gems/ruby-2.6.0/gems/nokogiri-1.10.1/lib/nokogiri/xml/builder.rb:391:in `insert'
/Users/user/.rvm/gems/ruby-2.6.0/gems/nokogiri-1.10.1/lib/nokogiri/xml/builder.rb:375:in `method_missing'
/Users/user/.rvm/gems/ruby-2.6.0/gems/allure-ruby-adaptor-api-0.7.2/lib/allure-ruby-adaptor-api/builder.rb:126:in `block (2 levels) in build!'
/Users/user/.rvm/gems/ruby-2.6.0/gems/nokogiri-1.10.1/lib/nokogiri/xml/builder.rb:293:in `initialize'
/Users/user/.rvm/gems/ruby-2.6.0/gems/allure-ruby-adaptor-api-0.7.2/lib/allure-ruby-adaptor-api/builder.rb:125:in `new'
/Users/user/.rvm/gems/ruby-2.6.0/gems/allure-ruby-adaptor-api-0.7.2/lib/allure-ruby-adaptor-api/builder.rb:125:in `block in build!'
/Users/user/.rvm/gems/ruby-2.6.0/gems/allure-ruby-adaptor-api-0.7.2/lib/allure-ruby-adaptor-api/builder.rb:124:in `each'
/Users/user/.rvm/gems/ruby-2.6.0/gems/allure-ruby-adaptor-api-0.7.2/lib/allure-ruby-adaptor-api/builder.rb:124:in `build!'
/Users/user/.rvm/gems/ruby-2.6.0/gems/allure-cucumber-0.6.1/lib/allure-cucumber/formatter.rb:144:in `after_features'
/Users/user/.rvm/gems/ruby-2.6.0/gems/cucumber-3.1.2/lib/cucumber/formatter/ignore_missing_messages.rb:11:in `method_missing'
/Users/user/.rvm/gems/ruby-2.6.0/gems/cucumber-3.1.2/lib/cucumber/formatter/legacy_api/adapter.rb:136:in `after'
/Users/user/.rvm/gems/ruby-2.6.0/gems/cucumber-3.1.2/lib/cucumber/formatter/legacy_api/adapter.rb:41:in `block in initialize'
/Users/user/.rvm/gems/ruby-2.6.0/gems/cucumber-core-3.2.1/lib/cucumber/core/event_bus.rb:34:in `block in broadcast'
/Users/user/.rvm/gems/ruby-2.6.0/gems/cucumber-core-3.2.1/lib/cucumber/core/event_bus.rb:34:in `each'
/Users/user/.rvm/gems/ruby-2.6.0/gems/cucumber-core-3.2.1/lib/cucumber/core/event_bus.rb:34:in `broadcast'
/Users/user/.rvm/gems/ruby-2.6.0/gems/cucumber-core-3.2.1/lib/cucumber/core/event_bus.rb:40:in `method_missing'
/Users/user/.rvm/gems/ruby-2.6.0/gems/cucumber-3.1.2/lib/cucumber/configuration.rb:33:in `notify'
/Users/user/.rvm/gems/ruby-2.6.0/gems/cucumber-3.1.2/lib/cucumber/runtime.rb:76:in `run!'
/Users/user/.rvm/gems/ruby-2.6.0/gems/cucumber-3.1.2/lib/cucumber/cli/main.rb:34:in `execute!'
/Users/user/.rvm/gems/ruby-2.6.0/gems/cucumber-3.1.2/bin/cucumber:9:in `<top (required)>'
/Users/user/.rvm/gems/ruby-2.6.0/bin/cucumber:23:in `load'
/Users/user/.rvm/gems/ruby-2.6.0/bin/cucumber:23:in `<main>'
/Users/user/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
/Users/user/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'

Took 70 seconds (1:10)
cucumbers Failed

**Comment by nareshnavinash** [comment]
This happens only when i add,

include Capybara::DSL

in the env.rb file in cucumber tests.

**Comment by andrcuns** [comment]
Doesn't seem to be related to allure at all

**Comment by nareshnavinash** [comment]
@andrcuns we can close this issue if not related to allure, I moved out of capybara and allure works like a charm.
