### ISSUE TITLE
categories.json file is not picked up when we are generating a allure report for the tests which are rerun for the failed test cases

### ISSUE THREAD

**Issue by nareshnavinash** [allure-framework/allure-cucumber#83]
Scenario 1: 

1. Run a cucumber test, have categories.json file in the allure report folder.
2. Now generate the allure report.

Output:
In the generated allure results, categories will be defined according to the categories.json

Scenario 2:

1. Run a cucumber test, have categories.json file in the allure report folder.
2. Rerun the cucumber test for the failed scenarios alone.
3. Now generate the allure report.

Output:
In the generated allure results, categories will not be defined according to the categories.json

**Comment by andrcuns** [comment]
Should be fixed in new adaptor implementation v2.13.0
