### ISSUE TITLE
Reports shows attachment which is irrelevant to the test cases

### ISSUE THREAD

**Issue by Dookiee** [allure-framework/allure-cucumber#84]
I have logged the information during the execution and file names are displayed properly. But reports attachment displays wrong information.  screenshots:
![Screenshot 2019-04-02 at 11 30 39 AM](https://user-images.githubusercontent.com/8068468/55379628-504a7880-553b-11e9-9eca-1fe9f4aad428.png)
![Screenshot 2019-04-02 at 11 32 10 AM](https://user-images.githubusercontent.com/8068468/55379634-53456900-553b-11e9-9be8-c5cf457ffff5.png)

**Comment by Dookiee** [comment]
The issue is identified. It is because of SHA256 generation. You are reading the content of the file and convert that as hash and stored in the file system. My test cases, having the same content on each file and it produces the same hashes. which causes faulty attachments to test cases.

**Comment by andrcuns** [comment]
Should be fixed in v2.13.0 as new commons api generate UUIDs without regards to file content.
