### ISSUE TITLE
Only one report getting generated with parallel execution 

### ISSUE THREAD

**Issue by FirstAM** [allure-framework/allure-cucumber#86]
Hi ! 
I am using appium and cucumber for parallel execution on multiple devices for one test case.  When I run multiple devices parallel, in folder with reports i see two different files for each devices . Unfortunately, when i generate reports i see only one case in list cases. How i can fix this , so that case see like a one test case for each devices ?

**Comment by andrcuns** [comment]
This is not an issue with cucumber ruby reporter but allure in general. I think You need to either add different arguments or somehow make custom names for tests.
