### ISSUE TITLE
uninitialized constant AllureCucumber::DSL (NameError)

### ISSUE THREAD

**Issue by pablo-gonzalez** [allure-framework/allure-cucumber#87]
I have installed the gem following the guide and when I try to run my project it says:

`pablo@pablo-Latitude-5480:~/projects/test$ cucumber -t @login
uninitialized constant AllureCucumber::DSL (NameError)
/home/pablo/projects/test/features/support/env.rb:13:in `<top (required)>'
/var/lib/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/glue/registry_and_more.rb:107:in `load'
/var/lib/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/glue/registry_and_more.rb:107:in `load_code_file'
/var/lib/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/runtime/support_code.rb:144:in `load_file'
/var/lib/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/runtime/support_code.rb:85:in `block in load_files!'
/var/lib/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/runtime/support_code.rb:84:in `each'
/var/lib/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/runtime/support_code.rb:84:in `load_files!'
/var/lib/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/runtime.rb:272:in `load_step_definitions'
/var/lib/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/runtime.rb:68:in `run!'
/var/lib/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/cli/main.rb:34:in `execute!'
/var/lib/gems/2.5.0/gems/cucumber-3.1.2/bin/cucumber:9:in `<top (required)>'
/usr/local/bin/cucumber:23:in `load'
/usr/local/bin/cucumber:23:in `<main>'
pablo@pablo-Latitude-5480:~/projects/test$ gem list

*** LOCAL GEMS ***

addressable (2.7.0)
allure-cucumber (2.13.0)
allure-ruby-commons (2.13.0)
appium_lib (9.17.0)
appium_lib_core (2.3.4)
backports (3.15.0)
bigdecimal (default: 1.3.4)
builder (3.2.3)
bundler (2.0.2)
capybara (3.29.0)
childprocess (3.0.0)
cmath (default: 1.0.0)
coderay (1.1.2)
creek (2.4.1)
csv (default: 1.0.0)
cucumber (3.1.2)
cucumber-core (3.2.1)
cucumber-expressions (6.0.1)
cucumber-tag_expressions (1.1.1)
cucumber-wire (0.0.1)
date (default: 1.0.0)
dbm (default: 1.0.0)
did_you_mean (1.2.0)
diff-lcs (1.3)
domain_name (0.5.20190701)
etc (default: 1.0.0)
eventmachine (1.2.7)
faye-websocket (0.10.9)
fcntl (default: 1.0.0)
fiddle (default: 1.0.0)
fileutils (default: 1.0.2)
gdbm (default: 2.0.0)
gherkin (5.1.0)
http (3.3.0)
http-cookie (1.0.3)
http-form_data (2.1.1)
http_parser.rb (0.6.0)
httparty (0.16.3)
io-console (default: 0.4.6)
ipaddr (default: 1.2.0)
json (2.2.0, default: 2.1.0)
macaddr (1.7.2)
method_source (0.9.2)
mime-types (3.3)
mime-types-data (3.2019.0904)
mimemagic (0.3.3)
mini_mime (1.0.2)
mini_portile2 (2.4.0)
minitest (5.10.3)
multi_json (1.13.1)
multi_test (0.1.2)
multi_xml (0.6.0)
net-telnet (0.1.1)
nokogiri (1.10.4)
openssl (default: 2.1.1)
power_assert (0.2.7)
pry (0.12.2)
psych (default: 3.0.2)
public_suffix (4.0.1)
rack (2.0.7)
rack-test (1.1.0)
rake (12.3.2, 12.3.1)
rdoc (default: 6.0.1)
regexp_parser (1.6.0)
report_builder (1.8)
require_all (2.0.0)
rspec (3.8.0)
rspec-core (3.8.2)
rspec-expectations (3.8.5)
rspec-mocks (3.8.2)
rspec-retry (0.6.1)
rspec-support (3.8.3)
rubyzip (1.3.0)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
selenium-webdriver (3.142.6)
stringio (default: 0.0.1)
strscan (default: 1.0.0)
systemu (2.6.5)
test-unit (3.2.5)
tomlrb (1.2.8)
unf (0.1.4)
unf_ext (0.0.7.6)
uuid (2.3.9)
webrick (default: 1.4.2)
websocket-driver (0.7.1)
websocket-extensions (0.1.4)
xpath (3.2.0)
zlib (default: 1.0.0)
pablo@pablo-Latitude-5480:~/projects/test$ uname -a
Linux pablo-Latitude-5480 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
pablo@pablo-Latitude-5480:~/projects/test$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
pablo@pablo-Latitude-5480:~/projects/test$ 
`

require "allure-cucumber" it is my env.rb file.
Also I have checked there the gem is installed:
`gem which allure-cucumber`
/var/lib/gems/2.5.0/gems/allure-cucumber-2.13.0/lib/allure-cucumber.rb

Inside allure-cucumber-2.13.0 I could not find any reference to DSL. For instance dsl.rb.
What I am doing wrong?

Thanks in advance,
Pablo

**Comment by andrcuns** [comment]
V 2.13.0 is a completely new implementation and is located here: https://github.com/allure-framework/allure-ruby/tree/master/allure-cucumber
